# Generated by Django 4.2.3 on 2023-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passby',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
