# Generated by Django 4.2.3 on 2023-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_passby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passby',
            field=models.CharField(max_length=100),
        ),
    ]
